config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/jaimeib/CEMS2:
      branch: main
      repo: https://github.com/jaimeib/CEMS2
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/jaimeib/CEMS2 git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-teal-quokka.sh
        container: qc.acc_homey-cardinal-newt
  QC.Doc:
    repos:
      github.com/jaimeib/CEMS2 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-ruby-earwig.sh
        container: qc.doc_homey-jade-butterfly
      github.com/jaimeib/CEMS2 git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-lavender-manatee.sh
        container: qc.doc_chewy-eggplant-newt
      github.com/jaimeib/CEMS2 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-thistle-numbat.sh
        container: qc.doc_smelly-amber-crane
  QC.Lic:
    repos:
      github.com/jaimeib/CEMS2 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-champagne-dollar.sh
        container: qc.lic_cozy-buff-hyrax
  QC.Sec:
    repos:
      github.com/jaimeib/CEMS2 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-bistre-squid.sh
        container: qc.sec_frumpy-coral-kingfisher
  QC.Sty:
    repos:
      github.com/jaimeib/CEMS2 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-maroon-quoll.sh
        container: qc.sty_frumpy-lime-spitz
      github.com/jaimeib/CEMS2 jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-cinnabar-saola.sh
        container: qc.sty_ready-ruby-magpie
  QC.Uni:
    repos:
      github.com/jaimeib/CEMS2 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-charcoal-bracke.sh
        container: qc.uni_gimpy-xanthic-zorse
  QC.Ver:
    repos:
      github.com/jaimeib/CEMS2 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-harlequin-heron.sh
        container: qc.ver_zippy-firebrick-indri
timeout: 5400
